# Generated by Django 6.0.2 on 2026-02-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricaldata',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='electricaldata',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
